### ISSUE TITLE
Spaces vs Tabs

### ISSUE THREAD

**Issue by fosslinux** [gophernicus/gophernicus#56]
A while ago I made a quite sweeping change across the codebase. Changing tabs to spaces; there were inconsistencies.

We should decide on our code style sooner rather than later.

Personally, I think we should go with tabs, since it is what gophernicus originally used and what most C projects use. Not to mention things like customizable width, etc. (I'm not very concerned either way; if Gophernicus was in Python I would say spaces...)

I am going to ask that people have a **sensible and reasonable** discussion. I will promptly remove any comments that make this a flamewar or argument.

Express your position. Do not attack people. Don't play devil's advocate; I only want to hear people's legitimate thoughts, not people trying to rile others up or just saying the opposite for the sake of it.

**Comment by Juangarcia8974** [comment]
In my opinion we should use spaces due to the fact that the tab measurement is different depending on the computer or software (I'm not sure what it is but i am certain it changes). In addition, the length of the spaces are the same for everyone no matter what. In addition, once you get used to it its no problem. I find it that 4 spaces is the ideal amount and it visually looks good.

**Comment by SiinaCutie** [comment]
>In my opinion we should use spaces due to the fact that the tab measurement is different depending on the computer or software 

This is precisely why we should use tabs. This lets users, especially those with accessibility needs, to adjust the tab size to fit their needs. For example: You can have yours look like 4 spaces the way you like, and someone else can have theirs set to 2 spaces with a bigger font, to accomodate poor eyesight. I can set mine to 8, but at the end of the day, the code isn't altered one bit, since tabs are user-defined.

**Comment by jamestomasino** [comment]
- [History of the project](https://github.com/gophernicus/gophernicus/blob/d829e6a347b28610a1f10f3a27bd8c804f5babb7/gophernicus.c) suggests tabs
- Community preference for the C language [is still with tabs](https://medium.com/@hoffa/400-000-github-repositories-1-billion-files-14-terabytes-of-code-spaces-or-tabs-7cfe0b5dd7fd#.j6ki2b7og)
- Tabs [are more accessible](https://github.com/gophernicus/gophernicus/issues/56#issuecomment-575902495)

In this particular repo, tabs seem the best choice.

**Comment by hb9kns** [comment]
Tabs.
Personally, I prefer spaces (though only one per level -- power to individualism! ^-^ ) but for gophernicus-historical and collaborative reasons, I am in favour of tabs.

**Comment by tallship** [comment]
It's C.

Tabs.

**Comment by fosslinux** [comment]
Since the current only open pull request is my own (I can deal with that), and we've given around 3 weeks for people to chime in; I think I will make the sweeping change (again, sorry) today on all .c/.h files.

Votes from here: 1 spaces/5 tabs (including @gbmor from thumbs).
2 people also said on irc.tilde.chat#gopher for tabs.

I think the community has made themselves clear.
