### ISSUE TITLE
Cancel freenode.

### ISSUE THREAD

**Issue by zcrayfish** [gophernicus/gophernicus#97]
In light of [recent](https://www.devever.net/~hl/freenode_abuse) [actions](https://twitter.com/i/web/status/1397455485712932865) by new freenode staff that can be interpreted as either [incompetence](https://pastebin.com/V55kG3Q1) or simply being openly hostile, can we have the IRC channel reference in README.md changed from freenode to libera.chat?

Thanks.

**Comment by tallship** [comment]
And further, I'm still in #gophernicus but Andrew Lee has usurped control over the channel, presumably sending others  who try to join to ##gophernicus, since that's the behavior for  other channels commandeered by him, as indicated in the snippet below: 

```
<tallship> jik
* #gophernicus :Cannot send to nick/channel
```
Can we somehow   kill this channel? or... what is the game plan, since we don't want others attempting to expect support ending up in either a dead channel that is parading about as an imposter or ending up in a `##` channel.
